name: vimgcov build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Install dependencies
      run: |
        pip install pytest pytest-cov gcovr
        sudo apt install libboost-all-dev pybind11-dev rapidjson-dev libgtest-dev libspdlog-dev

    - name: Configure CMake
      run: cmake -S . build -DCMAKE_C_FLAGS=--coverage -DCMAKE_CXX_FLAGS=--coverage -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build build -j`nproc`

    - name: Run tests
      run: CTEST_OUTPUT_ON_FAILURE=ON cmake --build build -j`nproc` --target test

    - name: Generate coverage report
      run: |
        mkdir -p coverage/cpp
        gcovr -r . --xml-pretty -o coverage/cpp/coverage.xml -e build

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/cpp/coverage.xml,./coverage/python/coverage.xml
        flags: unittests
        name: codecov-coverage
        fail_ci_if_error: true
